image: Visual Studio 2015

platform:
    - x86
    - x64

configuration:
    - Release

environment:
    BOOST_ROOT: C:/Libraries/boost_1_65_1

install:
    - git submodule update --init --recursive
    - call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%

before_build:
    - md build

build_script:
    - where cmake
    - cd build
    - cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DNIT_BUILD_CLI=OFF -DCMAKE_VERBOSE_MAKEFILE=ON
    - cmake --build .

test_script:
    - ctest --verbose
