sudo: false
dist: trusty

language: cpp

os: linux

compiler: gcc

env:
    global:
        secure: "bkWZMD6pP3f+WEfTjlSI6cig2uEKzogBq9mcC088pBpMk19eiWJOjtwxjoX/N1tlHBv4oxP5to3FfbCiqAQJtOMfpx5u5CbzpUK4w6WC/uK2n2G/CfmyOprMA3rQqfAGormCCVwVidWoZeDkXl43hPWGoJdA2n6TwDUNmKl9VwIZVrlwmgCdAd6YTAed5/kpNR32a2Jes/YtpbVvtiAsWoqCHkiDDk2g02LyRDzxI8pP0Qt/r6ebbyOeAoMeOId0b0kex4I+JSLO0cbf7OYQApxkAOShvlec4dZo1Yrdr3R05tuET6J4teOfd5ZndvLSUmbAxwoPkdBJpfIBToDA8KZVBku2UyDbUFAazz7/7zf3BMiE9tG73gplO4xlno67wHToEVcl9xkNrR5w6/prleXaElQU6tBKQDVOLoTRBkjmHfGFG7yEPXpEZRJl8x/ahKX9CAy0D3+0E4Y1oAVQyDc7XsayVQUPP5HbKvRLvAKG4Rf0x+qsyQKjwR73fyWRVIkcLzy37NewHdVjEj5gfr1bNnPfrAKhyq+pnpRg6KVYrs8AOATh0cEv+WL6w5lH05kkQxY5q6tlOCbbRyN+euCOY9CzaZ+Qmal6Kr9Gw3GvxDXcEpEJF/LaHjUJVYSdHHQS3bIl46s78QUlFUZX5Z1YazZYyWySx93egIYR1aQ="

addons:
    coverity_scan:
        project:
            name: "rakhimov/nit"
        notification_email: "ol.rakhimov@gmail.com"
        build_command_prepend: "cmake -DCMAKE_VERBOSE_MAKEFILE=ON .."
        build_command: "make -j 2"
        branch_pattern: "coverity-scan"
    apt:
        packages:
            - libboost-all-dev

before_script:
    - mkdir build
    - cd build

script:
    - echo "Done"
    - cat cov-int/build-log.txt
