sudo: false
dist: trusty

language: cpp

os: linux

compiler:
    - gcc
    - clang

env:
    matrix:
        - CONFIG=Debug
        - CONFIG=Release

addons:
    apt:
        packages:
            - libboost-all-dev

matrix:
    include:
        - os: osx
          compiler: clang
          env: CONFIG=Release
        - os: linux
          compiler: gcc
          env: CONFIG=Coverage
          addons:
              apt:
                  packages:
                      - libboost-all-dev
                      - lcov
          install:
              - pip install --user codecov
          script:
              - cd build
              - cmake .. -DCMAKE_BUILD_TYPE=Debug -DWITH_COVERAGE=ON
              - make -j 2
              - make test
              - cd ..
              - .travis/submit_codecov.sh

before_script:
    - mkdir build

script:
    - cd build
    - cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE="${CONFIG}" ..
    - make -j 2
    - ctest --verbose
